apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "student-api.fullname" . }}
  labels:
    {{- include "student-api.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.disruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "student-api.selectorLabels" . | nindent 6 }}
